services:
  - type: web
    name: todo-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn todo_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: todo_project.settings
